// import PersonalInfo from "./PersonalInfo";

export const jobTitles = [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Data Scientist",
    "Machine Learning Engineer",
    "Product Manager",
    "Graphic Designer",
    "UI/UX Designer",
    "Digital Marketing Specialist",
    "Content Writer",
    "SEO Specialist",
    "DevOps Engineer",
    "Database Administrator",
    "Cloud Architect",
    "Network Engineer",
    "Sales Executive",
    "Customer Support Specialist",
    "Human Resources Manager",
    "Operations Manager",
    "Finance Analyst",
    "Business Analyst",
    "Project Manager",
    "Quality Assurance Engineer",
    "IT Support Specialist",
    "Cybersecurity Analyst",
    "Electrical Engineer",
    "Mechanical Engineer",
    "Civil Engineer",
    "Marketing Manager",
    "Social Media Manager",
    "Copywriter",
    "Video Editor",
    "Animation Specialist",
    "Legal Advisor",
    "Accountant",
    "Research Scientist",
    "Medical Representative",
    "Pharmacist",
    "Teacher",
    "Lecturer",
    "Data Analyst",
    "Software Tester"
  ];

;
// suggetion for objective carrier:

export const careerObjectives = [
  "To secure a challenging role in a dynamic organization where I can utilize my skills, knowledge, and dedication to contribute to the company's growth while continuously enhancing my personal and professional development. I aim to work collaboratively with teams, adapt to new challenges, and deliver impactful results that align with organizational goals and values.",
  "To obtain a position as a Data Analyst where I can utilize my analytical and statistical skills to interpret complex data, provide valuable insights, and support decision-making processes. I aim to contribute to business growth while enhancing my technical abilities and keeping up with emerging data technologies to create measurable impacts in achieving organizational goals.",
  "To excel as a Digital Marketing Specialist by leveraging my creativity and analytical skills to design and implement impactful marketing campaigns. I aim to enhance brand visibility, drive engagement, and achieve measurable results while staying updated with the latest trends and tools in digital marketing to contribute effectively to the company’s growth and success.",
  "To secure a position as a Product Manager where I can apply my leadership and strategic planning skills to drive product development from ideation to execution. My goal is to collaborate with teams, solve user challenges, and deliver innovative solutions that meet market demands while achieving measurable business outcomes for the organization.",
  "To work as a Full Stack Developer where I can apply my expertise in both frontend and backend technologies to develop scalable, efficient, and user-friendly applications. I aim to contribute to organizational success through clean, maintainable code and by continuously learning and adapting to emerging technologies in the software development field.",
  "To obtain a role as a Quality Assurance Engineer where I can ensure the delivery of high-quality software products through systematic testing and analysis. I aim to identify and resolve issues effectively while enhancing product performance, meeting user expectations, and contributing to the company’s reputation for excellence in the competitive technology landscape.",
  "To become a successful Human Resources Manager where I can apply my skills in recruitment, employee relations, and organizational development to foster a positive work environment and drive employee engagement.",
  "To work as a Financial Analyst where I can utilize my expertise in financial modeling and analysis to support strategic decision-making and contribute to the financial health and growth of the organization.",
  "To secure a position as a Software Engineer where I can leverage my programming skills and problem-solving abilities to develop innovative software solutions that meet user needs and drive business success.",
  "To excel as a Customer Service Representative by providing exceptional service and support to customers, resolving issues efficiently, and contributing to customer satisfaction and loyalty.",
  "To obtain a role as a Project Manager where I can apply my organizational and leadership skills to manage projects from inception to completion, ensuring timely delivery and alignment with business objectives.",
  "To work as a Graphic Designer where I can utilize my creativity and design skills to create visually appealing and effective marketing materials that enhance brand identity and engagement.",
  "To become a successful Business Analyst where I can apply my analytical skills and business acumen to identify opportunities for improvement and drive business growth through data-driven insights.",
  "To secure a position as a Network Administrator where I can apply my technical expertise to manage and maintain network infrastructure, ensuring optimal performance and security.",
  "To work as a Content Writer where I can utilize my writing skills and creativity to produce engaging and informative content that resonates with target audiences and supports marketing objectives.",
  "To excel as a Sales Executive by leveraging my communication and negotiation skills to drive sales growth and build strong customer relationships.",
  "To obtain a role as a UX/UI Designer where I can apply my design skills and user-centered approach to create intuitive and engaging user experiences that enhance product usability.",
  "To work as a Data Scientist where I can utilize my expertise in machine learning and data analysis to uncover insights and drive data-driven decision-making.",
  "To become a successful Operations Manager where I can apply my skills in process optimization and resource management to improve operational efficiency and support business growth.",
  "To secure a position as a Marketing Manager where I can apply my strategic thinking and leadership skills to develop and execute marketing strategies that drive brand awareness and business success.",
  "To work as a Cybersecurity Analyst where I can apply my expertise in security protocols and threat analysis to protect organizational assets and ensure data security.",
  "To excel as a Supply Chain Manager by leveraging my skills in logistics and inventory management to optimize supply chain operations and support business objectives.",
  "To obtain a role as a Mechanical Engineer where I can apply my technical skills and engineering knowledge to design and develop innovative mechanical systems and solutions.",
  "To work as a Social Media Manager where I can utilize my creativity and communication skills to develop and execute social media strategies that enhance brand presence and engagement.",
  "To become a successful Environmental Scientist where I can apply my knowledge of environmental science and sustainability to address environmental challenges and promote sustainable practices.",
   "To secure a position as a Research Scientist where I can utilize my analytical skills and scientific knowledge to conduct research that contributes to advancements in my field and supports innovative solutions.",
  "To work as a Database Administrator where I can apply my expertise in database management and optimization to ensure data integrity, security, and availability for organizational needs.",
  "To excel as a Web Developer by leveraging my skills in HTML, CSS, and JavaScript to create responsive and user-friendly websites that enhance user experience and meet business objectives.",
  "To obtain a role as a Event Coordinator where I can utilize my organizational and communication skills to plan and execute successful events that meet client expectations and enhance brand visibility.",
  "To work as a Public Relations Specialist where I can apply my communication skills to manage public perception and build strong relationships with media and stakeholders.",
  "To become a successful Instructional Designer where I can apply my skills in curriculum development and educational technology to create engaging and effective learning experiences.",
  "To secure a position as a Cloud Engineer where I can utilize my expertise in cloud computing to design and implement scalable cloud solutions that meet business needs.",
  "To work as a Mobile App Developer where I can apply my programming skills to create innovative and user-friendly mobile applications that enhance user engagement and satisfaction.",
  "To excel as a SEO Specialist by leveraging my knowledge of search engine optimization techniques to improve website visibility and drive organic traffic.",
  "To obtain a role as a Data Engineer where I can utilize my skills in data architecture and ETL processes to build and maintain robust data pipelines that support analytics and business intelligence.",
  "To work as a Compliance Officer where I can apply my knowledge of regulations and standards to ensure organizational compliance and mitigate risks.",
  "To become a successful Technical Writer where I can utilize my writing skills to create clear and concise documentation that enhances user understanding and product usability.",
  "To secure a position as a Sales Manager where I can apply my leadership and strategic planning skills to drive sales performance and achieve revenue targets.",
  "To work as a Blockchain Developer where I can leverage my expertise in blockchain technology to design and implement secure and efficient decentralized applications.",
  "To excel as a Video Editor by utilizing my creativity and technical skills to produce high-quality video content that engages audiences and supports marketing initiatives.",
  "To obtain a role as a Fashion Designer where I can apply my creativity and design skills to create innovative and trend-setting fashion collections.",
  "To work as a Data Privacy Officer where I can utilize my knowledge of data protection regulations to ensure compliance and safeguard personal information.",
  "To become a successful E-commerce Manager where I can apply my skills in online retail and digital marketing to drive sales and enhance customer experience.",
  "To secure a position as a Logistics Coordinator where I can utilize my organizational skills to manage supply chain operations and ensure timely delivery of products.",
  "To work as a Research Analyst where I can apply my analytical skills to gather and interpret data that supports strategic decision-making and business growth.",
  "To excel as a Game Developer by leveraging my programming skills and creativity to design and develop engaging and interactive video games.",
  "To obtain a role as a Health and Safety Officer where I can apply my knowledge of safety regulations to promote a safe working environment and ensure compliance.",
  "To work as a Digital Content Strategist where I can utilize my skills in content creation and marketing to develop strategies that enhance brand engagement and visibility.",
  "To become a successful Interior Designer where I can apply my creativity and design skills to create functional and aesthetically pleasing spaces.",
  "To secure a position as a Telecommunications Engineer where I can utilize my technical expertise to design and implement communication systems that meet organizational needs.",
  "To work as a Nonprofit Manager where I can apply my leadership and organizational skills to drive initiatives that support community development and social impact.",
  "To excel as a Biotechnologist by leveraging my scientific knowledge to develop innovative solutions in healthcare and agriculture.",
  "To obtain a role as a User Researcher where I can apply my skills in qualitative and quantitative research to gather insights that inform product design and development.",
  "To work as a Financial Planner where I can utilize my expertise in personal finance to help clients achieve their financial goals and secure their financial future.",
  "To become a successful Art Director where I can apply my creativity and leadership skills to oversee visual projects and ensure alignment with brand identity.",
  "To secure a position as a Cybersecurity Consultant where I can utilize my expertise in security assessments and risk management to protect organizations from cyber threats.",
  "To work as a Data Visualization Specialist where I can apply my skills in data analysis and visualization tools to create compelling visual representations of data that support decision-making.",
  "To excel as a Product Marketing Manager by leveraging my marketing skills to develop and execute strategies that drive product adoption and market penetration.",
  "To obtain a role as a Supply Chain Analyst where I can utilize my analytical skills to optimize supply chain processes and improve operational efficiency.",
  "To work as a Renewable Energy Engineer where I can apply my engineering skills to develop sustainable energy solutions that contribute to environmental conservation and energy efficiency.",
  "To become a successful User Experience Researcher where I can apply my research skills to understand user needs and behaviors, informing product design and enhancing user satisfaction.",
  "To secure a position as a DevOps Engineer where I can utilize my skills in software development and IT operations to streamline processes and improve collaboration between development and operations teams.",
  "To work as a Brand Strategist where I can apply my marketing expertise to develop and implement brand strategies that enhance brand equity and drive customer loyalty.",
  "To excel as a Mobile UX Designer by leveraging my design skills to create intuitive and engaging user experiences for mobile applications.",
  "To obtain a role as a Corporate Trainer where I can utilize my skills in training and development to enhance employee skills and drive organizational performance.",
  "To work as a Data Compliance Specialist where I can apply my knowledge of data protection laws to ensure organizational compliance and protect sensitive information.",
  "To become a successful Event Planner where I can apply my organizational and creative skills to plan and execute memorable events that meet client expectations.",
  "To secure a position as a Software Tester where I can utilize my attention to detail and analytical skills to ensure the quality and functionality of software products.",
  "To work as a Research and Development Engineer where I can apply my engineering skills to innovate and develop new products that meet market needs.",
  "To excel as a Community Manager by leveraging my communication skills to build and engage online communities that enhance brand loyalty and customer engagement.",
  "To obtain a role as a Product Designer where I can apply my design skills to create user-centered products that meet customer needs and enhance user experience.",
  "To work as a Financial Auditor where I can utilize my analytical skills to assess financial records and ensure compliance with regulations and standards.",
  "To become a successful SEO Analyst where I can apply my knowledge of search engine algorithms to improve website rankings and drive organic traffic.",
  "To secure a position as a Technical Support Specialist where I can utilize my problem-solving skills to assist customers with technical issues and enhance their experience.",
  "To work as a Market Research Analyst where I can apply my analytical skills to gather and interpret market data, supporting strategic business decisions.",
  "To excel as a Cloud Solutions Architect by leveraging my expertise in cloud technologies to design and implement scalable cloud solutions that meet business requirements.",
  "To obtain a role as a Product Owner where I can apply my skills in agile methodologies to prioritize product features and ensure alignment with business goals.",
  "To work as a Social Impact Consultant where I can utilize my skills in strategy and analysis to help organizations create positive social change.",
  "To become a successful Digital Transformation Consultant where I can apply my expertise in technology and business processes to guide organizations through digital transformation initiatives.",
  "To secure a position as a Compliance Analyst where I can utilize my knowledge of regulations to assess and ensure compliance within the organization.",
  "To work as a User Interface Developer where I can apply my skills in front-end technologies to create visually appealing and functional user interfaces.",
  "To excel as a Health Informatics Specialist by leveraging my knowledge of healthcare and information technology to improve patient care and health outcomes.",
  "To obtain a role as a Business Development Executive where I can utilize my sales and negotiation skills to identify and pursue new business opportunities.",
  "To work as a Cybersecurity Engineer where I can apply my technical skills to design and implement security measures that protect organizational data and systems.",
  "To become a successful Data Governance Specialist where I can apply my knowledge of data management practices to ensure data quality and compliance.",
  "To secure a position as a User Experience Designer where I can utilize my design skills to create user-friendly interfaces that enhance user satisfaction.",
  "To work as a Product Analyst where I can apply my analytical skills to assess product performance and provide insights for product improvement.",
  "To excel as a Digital Advertising Specialist by leveraging my skills in online advertising to create and manage effective digital marketing campaigns.",
  "To obtain a role as a Business Intelligence Analyst where I can utilize my analytical skills to transform data into actionable insights that drive business strategy.",
  "To work as a Software Architect where I can apply my expertise in software design and architecture to create scalable and efficient software solutions.",
  "To become a successful Data Quality Analyst where I can apply my skills in data analysis to ensure the accuracy and integrity of data within the organization."
];
export const languageSuggetion = [
  // Popular Human Languages
  "English",
  "Hindi",
  "Spanish",
  "Mandarin",
  "French",
  "German",
  "Japanese",
  "Korean",
  "Arabic",
  "Portuguese",
  "Russian",
  "Italian",
  "Bengali",
  "Punjabi",
  "Urdu",
  "Turkish",
  "Dutch",
  "Swedish",
  "Tamil",
  "Gujarati",
  "Marathi",
  "Telugu",
  "Malayalam",
  "Thai",
  "Vietnamese",
  "Polish",
  "Czech",
];
